name: Samples C# .Net 8 Clients

on:
  push:
    paths:
      - samples/client/petstore/csharp/generichost/net8/**
      - samples/client/petstore/csharp/httpclient/net8/**
      - samples/client/petstore/csharp/restsharp/net8/**
      - samples/client/petstore/csharp/unityWebRequest/net8/**
  pull_request:
    paths:
      - samples/client/petstore/csharp/generichost/net8/**
      - samples/client/petstore/csharp/httpclient/net8/**
      - samples/client/petstore/csharp/restsharp/net8/**
      - samples/client/petstore/csharp/unityWebRequest/net8/**
jobs:
  build:
    name: Build .Net projects
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-manual-tests
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-net6.0
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-net6.0-nrt
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-net6.0-nrt-useSourceGeneration
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-net7.0-useDateTimeForDate
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-netcore-latest-allOf
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-netcore-latest-anyOf
          - samples/client/petstore/csharp/generichost/net8/OpenAPIClient-generichost-netcore-latest-oneOf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'
      - name: Build
        working-directory: ${{ matrix.sample }}
        run: dotnet build Org.OpenAPITools.sln
      - name: Test
        working-directory: ${{ matrix.sample }}
        run: dotnet test Org.OpenAPITools.sln
